"use client";

import { motion } from "framer-motion";
import { GlassCard } from "./GlassCard";
import { TrendingUp, Clock, AlertCircle } from "lucide-react";

export const ImpactCalculator = () => {
  return (
    <section id="impact" className="max-w-6xl mx-auto px-6 py-48 border-y border-[#1F1F1F] bg-white/[0.01]">
      <div className="mb-24">
        <h2 className="title-understated mb-6">Structural Impact</h2>
        <p className="text-[#F2F0E9]/40 max-w-xl font-medium mb-4 text-lg">Quantifying the operational advantages of autonomous logical systems.</p>
        <p className="text-[10px] uppercase font-black tracking-[0.3em] text-accent-red opacity-40">The ROI generated by Factoric Workforce.</p>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
        <div className="flex flex-col">
          <div className="text-5xl font-light mb-6 tracking-tighter text-accent-red">120<span className="text-xl text-[#F2F0E9]/20">/mo</span></div>
          <div className="text-[10px] uppercase font-black tracking-[0.4em] text-[#F2F0E9]/20 mb-6">Logical Man-Hours Recovered</div>
          <p className="text-sm text-[#F2F0E9]/50 leading-relaxed max-w-xs font-medium">
            Autonomous triage systems eliminate manual intent-processing, allowing human capital to focus on strategic execution.
          </p>
        </div>

        <div className="flex flex-col">
          <div className="text-5xl font-light mb-6 tracking-tighter text-accent-red">90<span className="text-xl text-[#F2F0E9]/20">%</span></div>
          <div className="text-[10px] uppercase font-black tracking-[0.4em] text-[#F2F0E9]/20 mb-6">Latency Reduction</div>
          <p className="text-sm text-[#F2F0E9]/50 leading-relaxed max-w-xs font-medium">
            Response times are reduced to seconds. Precision is maintained at scale through structural neural optimization.
          </p>
        </div>

        <div className="flex flex-col">
          <div className="text-5xl font-light mb-6 tracking-tighter text-accent-red">Zero</div>
          <div className="text-[10px] uppercase font-black tracking-[0.4em] text-[#F2F0E9]/20 mb-6">Operational Leakage</div>
          <p className="text-sm text-[#F2F0E9]/50 leading-relaxed max-w-xs font-medium">
            Predictive growth models identify and eliminate revenue gaps before they manifest in operational reporting.
          </p>
        </div>
      </div>
    </section>
  );
};
